services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: b-app-ffa
    hostname: b-app-ffa
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend
    volumes:
      - app_logs:/app/logs

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-JoseCamiloCela678}
      - POSTGRES_DB=ffa
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "10080:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    hostname: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
  redis_data:
  app_logs:
